// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pittheo.projects.template.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import pittheo.projects.template.domain.ImageInfo;

privileged aspect ImageInfoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ImageInfoDataOnDemand: @Component;
    
    private Random ImageInfoDataOnDemand.rnd = new SecureRandom();
    
    private List<ImageInfo> ImageInfoDataOnDemand.data;
    
    public ImageInfo ImageInfoDataOnDemand.getNewTransientImageInfo(int index) {
        ImageInfo obj = new ImageInfo();
        setAuthor(obj, index);
        setCreatedAt(obj, index);
        setDescription(obj, index);
        setFilename(obj, index);
        setOriginalPath(obj, index);
        setThumbnailPath(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void ImageInfoDataOnDemand.setAuthor(ImageInfo obj, int index) {
        String author = "author_" + index;
        obj.setAuthor(author);
    }
    
    public void ImageInfoDataOnDemand.setCreatedAt(ImageInfo obj, int index) {
        Date createdAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedAt(createdAt);
    }
    
    public void ImageInfoDataOnDemand.setDescription(ImageInfo obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ImageInfoDataOnDemand.setFilename(ImageInfo obj, int index) {
        String filename = "filename_" + index;
        obj.setFilename(filename);
    }
    
    public void ImageInfoDataOnDemand.setOriginalPath(ImageInfo obj, int index) {
        String originalPath = "originalPath_" + index;
        obj.setOriginalPath(originalPath);
    }
    
    public void ImageInfoDataOnDemand.setThumbnailPath(ImageInfo obj, int index) {
        String thumbnailPath = "thumbnailPath_" + index;
        obj.setThumbnailPath(thumbnailPath);
    }
    
    public void ImageInfoDataOnDemand.setTitle(ImageInfo obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public ImageInfo ImageInfoDataOnDemand.getSpecificImageInfo(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ImageInfo obj = data.get(index);
        return ImageInfo.findImageInfo(obj.getId());
    }
    
    public ImageInfo ImageInfoDataOnDemand.getRandomImageInfo() {
        init();
        ImageInfo obj = data.get(rnd.nextInt(data.size()));
        return ImageInfo.findImageInfo(obj.getId());
    }
    
    public boolean ImageInfoDataOnDemand.modifyImageInfo(ImageInfo obj) {
        return false;
    }
    
    public void ImageInfoDataOnDemand.init() {
        data = ImageInfo.findImageInfoEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ImageInfo' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<pittheo.projects.template.domain.ImageInfo>();
        for (int i = 0; i < 10; i++) {
            ImageInfo obj = getNewTransientImageInfo(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
