// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pittheo.projects.template.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import pittheo.projects.template.domain.MessageDataOnDemand;

privileged aspect MessageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MessageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MessageIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MessageIntegrationTest: @Transactional;
    
    @Autowired
    private MessageDataOnDemand MessageIntegrationTest.dod;
    
    @Test
    public void MessageIntegrationTest.testCountMessages() {
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        long count = pittheo.projects.template.domain.Message.countMessages();
        org.junit.Assert.assertTrue("Counter for 'Message' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MessageIntegrationTest.testFindMessage() {
        pittheo.projects.template.domain.Message obj = dod.getRandomMessage();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = pittheo.projects.template.domain.Message.findMessage(id);
        org.junit.Assert.assertNotNull("Find method for 'Message' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Message' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MessageIntegrationTest.testFindAllMessages() {
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        long count = pittheo.projects.template.domain.Message.countMessages();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Message', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<pittheo.projects.template.domain.Message> result = pittheo.projects.template.domain.Message.findAllMessages();
        org.junit.Assert.assertNotNull("Find all method for 'Message' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Message' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MessageIntegrationTest.testFindMessageEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        long count = pittheo.projects.template.domain.Message.countMessages();
        if (count > 20) count = 20;
        java.util.List<pittheo.projects.template.domain.Message> result = pittheo.projects.template.domain.Message.findMessageEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Message' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Message' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MessageIntegrationTest.testFlush() {
        pittheo.projects.template.domain.Message obj = dod.getRandomMessage();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = pittheo.projects.template.domain.Message.findMessage(id);
        org.junit.Assert.assertNotNull("Find method for 'Message' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMessage(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Message' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MessageIntegrationTest.testMerge() {
        pittheo.projects.template.domain.Message obj = dod.getRandomMessage();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = pittheo.projects.template.domain.Message.findMessage(id);
        boolean modified =  dod.modifyMessage(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        pittheo.projects.template.domain.Message merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Message' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MessageIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", dod.getRandomMessage());
        pittheo.projects.template.domain.Message obj = dod.getNewTransientMessage(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Message' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Message' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MessageIntegrationTest.testRemove() {
        pittheo.projects.template.domain.Message obj = dod.getRandomMessage();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Message' failed to provide an identifier", id);
        obj = pittheo.projects.template.domain.Message.findMessage(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Message' with identifier '" + id + "'", pittheo.projects.template.domain.Message.findMessage(id));
    }
    
}
