// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pittheo.projects.template.domain;

import java.lang.Boolean;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import pittheo.projects.template.domain.UserAccount;
import pittheo.projects.template.domain.UserProfile;
import pittheo.projects.template.domain.UserProfileDataOnDemand;

privileged aspect UserAccountDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserAccountDataOnDemand: @Component;
    
    private Random UserAccountDataOnDemand.rnd = new SecureRandom();
    
    private List<UserAccount> UserAccountDataOnDemand.data;
    
    @Autowired
    private UserProfileDataOnDemand UserAccountDataOnDemand.userProfileDataOnDemand;
    
    public UserAccount UserAccountDataOnDemand.getNewTransientUserAccount(int index) {
        UserAccount obj = new UserAccount();
        setCreatedAt(obj, index);
        setEmail(obj, index);
        setFromRegistration(obj, index);
        setHash(obj, index);
        setPassword(obj, index);
        setPriviledges(obj, index);
        setProfile(obj, index);
        setUsername(obj, index);
        setVerified(obj, index);
        setVerifiedAt(obj, index);
        return obj;
    }
    
    public void UserAccountDataOnDemand.setCreatedAt(UserAccount obj, int index) {
        Date createdAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedAt(createdAt);
    }
    
    public void UserAccountDataOnDemand.setEmail(UserAccount obj, int index) {
        String email = "email_" + index;
        obj.setEmail(email);
    }
    
    public void UserAccountDataOnDemand.setFromRegistration(UserAccount obj, int index) {
        Boolean fromRegistration = Boolean.TRUE;
        obj.setFromRegistration(fromRegistration);
    }
    
    public void UserAccountDataOnDemand.setHash(UserAccount obj, int index) {
        String hash = "hash_" + index;
        obj.setHash(hash);
    }
    
    public void UserAccountDataOnDemand.setPassword(UserAccount obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public void UserAccountDataOnDemand.setPriviledges(UserAccount obj, int index) {
        String priviledges = "priviledges_" + index;
        obj.setPriviledges(priviledges);
    }
    
    public void UserAccountDataOnDemand.setProfile(UserAccount obj, int index) {
        UserProfile profile = userProfileDataOnDemand.getRandomUserProfile();
        obj.setProfile(profile);
    }
    
    public void UserAccountDataOnDemand.setUsername(UserAccount obj, int index) {
        String username = "username_" + index;
        obj.setUsername(username);
    }
    
    public void UserAccountDataOnDemand.setVerified(UserAccount obj, int index) {
        Boolean verified = Boolean.TRUE;
        obj.setVerified(verified);
    }
    
    public void UserAccountDataOnDemand.setVerifiedAt(UserAccount obj, int index) {
        Date verifiedAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setVerifiedAt(verifiedAt);
    }
    
    public UserAccount UserAccountDataOnDemand.getSpecificUserAccount(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        UserAccount obj = data.get(index);
        return UserAccount.findUserAccount(obj.getId());
    }
    
    public UserAccount UserAccountDataOnDemand.getRandomUserAccount() {
        init();
        UserAccount obj = data.get(rnd.nextInt(data.size()));
        return UserAccount.findUserAccount(obj.getId());
    }
    
    public boolean UserAccountDataOnDemand.modifyUserAccount(UserAccount obj) {
        return false;
    }
    
    public void UserAccountDataOnDemand.init() {
        data = UserAccount.findUserAccountEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'UserAccount' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<pittheo.projects.template.domain.UserAccount>();
        for (int i = 0; i < 10; i++) {
            UserAccount obj = getNewTransientUserAccount(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
